/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import AppPackage.AnimationClass;
import java.awt.Desktop;
import java.net.URI;
import javafx.animation.Animation;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public void OpenInternet(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlaCalculadora = new javax.swing.JLabel();
        jLabelInternet1 = new javax.swing.JLabel();
        jLabelCalculadora = new javax.swing.JLabel();
        jLabelMusica = new javax.swing.JLabel();
        jlaMundo = new javax.swing.JLabel();
        jlaMusica = new javax.swing.JLabel();
        jpingreso = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpMenu = new javax.swing.JLabel();
        jpMenu1 = new javax.swing.JLabel();
        jpMenu2 = new javax.swing.JLabel();
        jpMenu3 = new javax.swing.JLabel();
        jpMenu4 = new javax.swing.JLabel();
        jpMenu5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jlaCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        jlaCalculadora.setText("jLabel16");

        jLabelInternet1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        jLabelInternet1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelInternet1MouseClicked(evt);
            }
        });

        jLabelCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Calculator_32px.png"))); // NOI18N
        jLabelCalculadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCalculadoraMouseClicked(evt);
            }
        });

        jLabelMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Musical_Notes_32px.png"))); // NOI18N

        jlaMundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Globe_32px.png"))); // NOI18N
        jlaMundo.setText("jLabel18");

        jlaMusica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Musical_Notes_32px.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 1050, 575));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpingreso.setBackground(new java.awt.Color(255, 255, 255));
        jpingreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jpingreso.setForeground(new java.awt.Color(255, 255, 255));
        jpingreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("Password: ");
        jpingreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, -1));

        jLabel8.setBackground(new java.awt.Color(238, 112, 82));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(238, 112, 82));
        jLabel8.setText("User: ");
        jpingreso.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_User_96px_2.png"))); // NOI18N
        jpingreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 100, 90));

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.setText("Ingrese Usuario");
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jpingreso.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 180, 30));
        jpingreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 220, 20));
        jpingreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 220, 20));

        jPasswordField1.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        jpingreso.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_customer_32px_1.png"))); // NOI18N
        jpingreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Key_32px.png"))); // NOI18N
        jpingreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Menu_32px.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jpingreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Enter_ON.png"))); // NOI18N
        jpingreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 100, 40));

        getContentPane().add(jpingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));
        jpingreso.getAccessibleContext().setAccessibleName("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Maintenance_96px.png"))); // NOI18N
        jpMenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenuMouseMoved(evt);
            }
        });
        jpMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenuMouseExited(evt);
            }
        });
        jPanel1.add(jpMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 160, 130));

        jpMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Today_96px.png"))); // NOI18N
        jpMenu1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenu1MouseMoved(evt);
            }
        });
        jpMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMenu1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenu1MouseExited(evt);
            }
        });
        jPanel1.add(jpMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 160, 130));

        jpMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Google_Drive_96px.png"))); // NOI18N
        jpMenu2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenu2MouseMoved(evt);
            }
        });
        jpMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMenu2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenu2MouseExited(evt);
            }
        });
        jPanel1.add(jpMenu2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 160, 130));

        jpMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Clock_96px.png"))); // NOI18N
        jpMenu3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenu3MouseMoved(evt);
            }
        });
        jpMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMenu3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenu3MouseExited(evt);
            }
        });
        jPanel1.add(jpMenu3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 160, 130));

        jpMenu4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Handshake_96px.png"))); // NOI18N
        jpMenu4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenu4MouseMoved(evt);
            }
        });
        jpMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMenu4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenu4MouseExited(evt);
            }
        });
        jPanel1.add(jpMenu4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 160, 130));

        jpMenu5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jpMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Idea_96px.png"))); // NOI18N
        jpMenu5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jpMenu5MouseMoved(evt);
            }
        });
        jpMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpMenu5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpMenu5MouseExited(evt);
            }
        });
        jPanel1.add(jpMenu5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 160, 130));

        jLabel6.setBackground(new java.awt.Color(255, 99, 71));
        jLabel6.setForeground(new java.awt.Color(255, 99, 71));
        jLabel6.setText("Drive");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 99, 71));
        jLabel7.setForeground(new java.awt.Color(255, 99, 71));
        jLabel7.setText("Programado");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 99, 71));
        jLabel9.setForeground(new java.awt.Color(255, 99, 71));
        jLabel9.setText("Cronograma");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 99, 71));
        jLabel10.setForeground(new java.awt.Color(255, 99, 71));
        jLabel10.setText("Mantenimiento");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 20));

        jLabel11.setBackground(new java.awt.Color(255, 99, 71));
        jLabel11.setForeground(new java.awt.Color(255, 99, 71));
        jLabel11.setText("    Notas");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, -1, -1));

        jLabel12.setBackground(new java.awt.Color(255, 99, 71));
        jLabel12.setForeground(new java.awt.Color(255, 99, 71));
        jLabel12.setText("Socios");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jTextField2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Buscar..");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 180, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Search_32px_2.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 760, 540));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Multiply_32px.png"))); // NOI18N
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, -1, 40));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jpMenu1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu1MouseMoved
        jpMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenu1MouseMoved

    private void jpMenu2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu2MouseMoved
        jpMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenu2MouseMoved

    private void jpMenu3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu3MouseMoved
        jpMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenu3MouseMoved

    private void jpMenu4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu4MouseMoved
       jpMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenu4MouseMoved

    private void jpMenu5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu5MouseMoved
        jpMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenu5MouseMoved

    private void jpMenuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuMouseMoved
        jpMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153,153,153)));
    }//GEN-LAST:event_jpMenuMouseMoved

    private void jpMenu1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu1MouseEntered
        jpMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu1MouseEntered

    private void jpMenu2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu2MouseEntered
        jpMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu2MouseEntered

    private void jpMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu3MouseEntered
        jpMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu3MouseEntered

    private void jpMenu4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu4MouseEntered
    jpMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu4MouseEntered

    private void jpMenu5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jpMenu5MouseEntered

    private void jpMenu1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu1MouseExited
        jpMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu1MouseExited

    private void jpMenu2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu2MouseExited
        jpMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu2MouseExited

    private void jpMenu3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu3MouseExited
        jpMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu3MouseExited

    private void jpMenu4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu4MouseExited
        jpMenu4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu4MouseExited

    private void jpMenu5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenu5MouseExited
        jpMenu5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenu5MouseExited

    private void jpMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpMenuMouseExited
        jpMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255,255,255)));
    }//GEN-LAST:event_jpMenuMouseExited

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       /*
        AnimationClass calculadora = new AnimationClass();
       calculadora.jLabelXRight(-40,10,10,5, jlaCalculadora);
       //<--
       AnimationClass calculadoraa = new AnimationClass();
       calculadoraa.jLabelXLeft(-40,10,10,5, jlaCalculadora);
       
       
       AnimationClass internet = new AnimationClass();
       internet.jLabelXRight(10,-40,10,5, jLabelInternet1);
       //<--
       AnimationClass internett = new AnimationClass();
       internett.jLabelXLeft(-40,10,10,5, jLabelInternet1);
       
       
       AnimationClass musica = new AnimationClass();
       musica.jLabelXRight(10,-40,10,5, jLabelMusica);
       //<--
       AnimationClass musicaa = new AnimationClass();
       musicaa.jLabelXLeft(-40,10,10,5, jLabelMusica);
       */
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabelInternet1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelInternet1MouseClicked
        
    }//GEN-LAST:event_jLabelInternet1MouseClicked

    private void jLabelCalculadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCalculadoraMouseClicked
        
    }//GEN-LAST:event_jLabelCalculadoraMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
      this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        int dialog =JOptionPane.YES_NO_CANCEL_OPTION;
        int result = JOptionPane.showConfirmDialog(null,"Desea Salir del LOgin?","Exit",dialog);
        if(result == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel16MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCalculadora;
    private javax.swing.JLabel jLabelInternet1;
    private javax.swing.JLabel jLabelMusica;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel jlaCalculadora;
    private javax.swing.JLabel jlaMundo;
    private javax.swing.JLabel jlaMusica;
    private javax.swing.JLabel jpMenu;
    private javax.swing.JLabel jpMenu1;
    private javax.swing.JLabel jpMenu2;
    private javax.swing.JLabel jpMenu3;
    private javax.swing.JLabel jpMenu4;
    private javax.swing.JLabel jpMenu5;
    private javax.swing.JPanel jpingreso;
    // End of variables declaration//GEN-END:variables
}
